//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Pfe.GetUserRights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Pfe.GetUserRights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective user rights for: {0}.
        /// </summary>
        internal static string strEffectiveRights {
            get {
                return ResourceManager.GetString("strEffectiveRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to principal.
        /// </summary>
        internal static string strPrncipal {
            get {
                return ResourceManager.GetString("strPrncipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal should have value.
        /// </summary>
        internal static string strPrncipalNull {
            get {
                return ResourceManager.GetString("strPrncipalNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE:.
        /// </summary>
        internal static string strUsage {
            get {
                return ResourceManager.GetString("strUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     GetUserRights [[domain\]username].
        /// </summary>
        internal static string strUsageCmd {
            get {
                return ResourceManager.GetString("strUsageCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If username is omitted Effective rights are evaluated for logged on user..
        /// </summary>
        internal static string strUsageExplain {
            get {
                return ResourceManager.GetString("strUsageExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userName.
        /// </summary>
        internal static string strUserName {
            get {
                return ResourceManager.GetString("strUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name should have value.
        /// </summary>
        internal static string strUserNameNull {
            get {
                return ResourceManager.GetString("strUserNameNull", resourceCulture);
            }
        }
    }
}
